### PR TITLE
Mark answered questions

### LINKED ISSUE #2: Add "done" (asked) in the display
Add "done" (asked) in the display

### PR DESCRIPTION
**Pull request by jcsirot**
This PR:

- adds an 'answered' boolean in `Question` class
- adds a button icon in the UI in order to toggle the answered flag
- automatically marks answered demoted questions

Fixes #2

### CODE REVIEW

**Comment by sunix** [comment]
@jcsirot is that a mistake ?
this PR has been merged downstream: https://github.com/parisjug/live-stream-question/pull/1

**Comment by jcsirot** [comment]
Yes it is a mistake. I wrongly choose the upstream when I created to PR 😕

**Comment by PerfectSlayer** [comment]
Hi @jcsirot 

The feature seems interesting!
Could you rework the PR to only push 92109169b115e6fb58cc9f3a3afaac5bc9fe3a20 and its fixup?

I will update the README accordingly.
Thanks!

**Comment by jcsirot** [comment]
Sure, I'm going to see how to remove the unrelated commits

**Comment by PerfectSlayer** [comment]
If you run a `git rebase -i master` from your clone branch, it should show all the commits... So just mark as _skip_ the ones to remove and `git push --force` the branch. 
The PR should automagically update itself 😅  Thanks!

**Comment by jcsirot** [comment]
Done!

**Comment by PerfectSlayer** [comment]
Thanks!

That looks to be a nice addition. I especially like the fact it is automatically marked as answered when unpinned.

I might remove the `asked` from `Question` constructor as it should always been un-asked when created.
And maybe use map and isPresent on optional but I am not sure that using map to apply a side-effect is a good idea 🤷 

```java
// From
Optional<Question> questionOptional = this.questions.stream()
                .filter(question -> question.uuid.equals(uuid))
                .findAny();
        if (questionOptional.isEmpty()) {
            return false;
        }
        questionOptional.get().answered = !questionOptional.get().answered;
        return true;
// to
return this.questions.stream()
                .filter(question -> question.uuid.equals(uuid))
                .findAny();
                .map(q -> {q.answered = !q.answered; return q;})
                .isPresent();
```

**Comment by PerfectSlayer** [comment]
Thanks for the update!

**Pull request merged**
